#!/bin/bash

# Set wallpaper based on time of day and generate colorscheme
TIME=$(date +"%-H")
DATE=$(date +"%d-%m-%Y")

if [[ -f "$HOME/.config/prayerhistory/$DATE.txt" ]]; then
	PRAYER_NAME=$(bash $HOME/.config/scripts/prayer.sh -n)
	case $PRAYER_NAME in
		"Fajr") FOLDER="dawn";;
		"Sunrise") FOLDER="morning";;
		"Dhuhr") FOLDER="noon";;
		"Asr") FOLDER="afternoon";;
		"Maghrib") FOLDER="sunset";;
		"Isha" | "Midnight" | "Last Third") FOLDER="night";;
	esac
else
	if [[ $TIME -ge 4 && $TIME -lt 7 ]]; then
		FOLDER="dawn"
	elif [[ $TIME -ge 7 && $TIME -lt 11 ]]; then
		FOLDER="morning"
	elif [[ $TIME -ge 11 && $TIME -lt 15 ]]; then
		FOLDER="noon"
	elif [[ $TIME -ge 15 && $TIME -lt 18 ]]; then
		FOLDER="afternoon"
	elif [[ $TIME -ge 18 && $TIME -lt 20 ]]; then
		FOLDER="sunset"
	elif [[ $TIME -ge 20 ]] || [[ $TIME -lt 4 ]]; then
		FOLDER="night"
	fi
fi

if [ "$1" == "-c" ]; then
	THEME="element-icon { size: 115px; margin: 0; }\
		element-text { size: 0px; margin: 0; padding: 0; }\
		listview { columns: 4; lines: 3; spacing: 8px; }\
		element { padding: 0; orientation: vertical; children: [element-icon]; }\
		mainbox { children: [listview]; }\
		window { height: 740px; width: 800px; }"

	WALLPAPER=$(ls $HOME/.config/wallpapers/$FOLDER/ | while read A; do echo -en "$A\x00icon\x1f$HOME/.config/wallpapers/$FOLDER/$A\n"; done | rofi -dmenu -p " Wallpaper" -theme-str "$THEME")
	if [ -z "$WALLPAPER" ]; then exit; fi
else
	WALLPAPER=$(ls -1 $HOME/.config/wallpapers/$FOLDER/ | sort --random-sort | head -1)
fi

WALLPAPER="$HOME/.config/wallpapers/$FOLDER/$WALLPAPER"
wal -si $WALLPAPER

# Get background and foreground colors
BG=$(cat $HOME/.cache/wal/colors.json | jq -r .special.background)
FG=$(cat $HOME/.cache/wal/colors.json | jq -r .special.foreground)

# Dim or lighten color $1 by a given factor $2
dimlightcol() {
	local color="${1#"#"}"
	local factor="${2:-0.8}"
	local dim_color=""

	for i in 0 2 4; do
		local hex=${color:$i:2}
		local dec=$((16#$hex))
		local dim=$(printf "%.0f" $(echo "$dec * $factor" | bc))

		if ((dim > 255)); then
			dim=255
		fi

		dim_color+=$(printf "%02x" $dim)
	done

	printf "#%s" "$dim_color"
}

# Give each color generated by pywal a score and select the top 4 best accent color candidates
get_accent_colors() {
	readarray -t generated_colors < <(jq -r '.colors | to_entries[] | select(.key | test("^color[1-6]$")) | .value' "$1")

	# Give each color a score (higher score = better candidate to be an accent color)
	local scored_colors=()

	for color in "${generated_colors[@]}"; do
		# Separate color channels
		local r=$((16#${color:1:2}))
		local g=$((16#${color:3:2}))
		local b=$((16#${color:5:2}))

		# Calculate saturation
		local max=$r; [ $g -gt $max ] && max=$g; [ $b -gt $max ] && max=$b
		local min=$r; [ $g -lt $min ] && min=$g; [ $b -lt $min ] && min=$b

		local saturation=0
		if [ $max -ne 0 ]; then
			saturation=$(( ((max - min) * 100) / max ))
		fi

		# Calculate color brightness
		local brightness=$(( (max * 100) / 255 ))

		# Calculate color score (ignoring low-saturation colors)
		local score=0

		if [ $saturation -ge 15 ]; then
			score=$(( (saturation * 2) + brightness ))
		fi

		scored_colors+=("$score $r $g $b $color")
	done

	# Sort scored colors
	readarray -t scored_colors < <(printf "%s\n" "${scored_colors[@]}" | sort -nr)

	local accent_colors=()
	local selected_rgb=()

	# Select distinct colors
	for entry in "${scored_colors[@]}"; do
		read -r score r1 g1 b1 color <<< "$entry"

		local is_too_similar=false

		# Calculate distance with all colors already selected
		for selected in "${selected_rgb[@]}"; do
			read -r r2 g2 b2 <<< "$selected"

			distance=$(( 2*(r1-r2)**2 + 4*(g1-g2)**2 + 3*(b1-b2)**2 ))

			if [ $distance -lt 15000 ]; then
				is_too_similar=true
				break
			fi
		done

		# Color is distinct from all colors already selected
		if [ "$is_too_similar" = false ]; then
			accent_colors+=("$color")
			selected_rgb+=("$r1 $g1 $b1")
		fi

		# Only need 4 accent colors
		if [ ${#accent_colors[@]} -eq 4 ]; then
			break
		fi
	done

	# Fallback in case 4 distinct colors could not be selected (all candidate colors are similar)
	if [ ${#accent_colors[@]} -lt 4 ]; then
		for entry in "${scored_colors[@]}"; do
			read -r score r g b color <<< "$entry"

			# Skip colors that were already selected
			if [[ " ${accent_colors[@]} " =~ " $color " ]]; then
				continue
			fi

			accent_colors+=("$color")

			# Only need 4 accent colors
			if [ ${#accent_colors[@]} -eq 4 ]; then
				break
			fi
		done
	fi

	# Return selected accent colors
	printf "%s\n" "${accent_colors[@]}"
}

# If color is dark then set text to FG for good readability, otherwise set text to BG
check_brightness() {
	local color=$1
	local threshold=103

	local r=$((16#${color:1:2}))
	local g=$((16#${color:3:2}))
	local b=$((16#${color:5:2}))

	# Calculate perceived brightness using YIQ formula
	local brightness=$(( (r * 299 + g * 587 + b * 114) / 1000 ))

	if [ $brightness -lt $threshold ]; then
		echo "$FG"
	else
		echo "$BG"
	fi
}

# Templates
firefox_dirs=("$HOME"/.config/mozilla/firefox/*.auto-arch)

FIREFOX_DIR="${firefox_dirs[0]}/chrome"

declare -A config_map=(
	["$HOME/.config/waybar/style_dwl.bak"]="$HOME/.config/waybar/style.css"
	["$HOME/.config/rofi/theme.bak"]="$HOME/.config/rofi/theme.rasi"
	["$HOME/.config/dunst/dunstrc.bak"]="$HOME/.config/dunst/dunstrc"
	["$FIREFOX_DIR/userChrome.bak"]="$FIREFOX_DIR/userChrome.css"
	["$FIREFOX_DIR/userContent.bak"]="$FIREFOX_DIR/userContent.css"
)

for template in "${!config_map[@]}"; do
	cp "$template" "${config_map[$template]}"
done

# Dimmed/lightened versions of BG and FG
LIGHTBG=$(dimlightcol $BG 1.5)
LIGHTERBG=$(dimlightcol $BG 2.0)

DIMFG=$(dimlightcol $FG 0.55)

# Declare all colors
color_names=("FG" "DIMFG" "BG" "LIGHTBG" "LIGHTERBG")
accent_colors=($(get_accent_colors "$HOME/.cache/wal/colors.json"))

for index in "${!accent_colors[@]}"; do
	color_number=$(( index + 1 ))
	color_hex="${accent_colors[$index]}"

	color_name="COL${color_number}"
	dim_color_name="DIMCOL${color_number}"
	fg_color_name="FGCOL${color_number}"

	color_names+=("$color_name" "$dim_color_name" "$fg_color_name")

	declare "$color_name=$color_hex"
	declare "$dim_color_name=$(dimlightcol "$color_hex")"
	declare "$fg_color_name=$(check_brightness "$color_hex")"
done

# Substitute color hex values into configurations
for config in "${config_map[@]}"; do
	for color in "${color_names[@]}"; do
		sed -i "s/__${color}__/${!color}/" "$config"
	done
done

# Special handling for dwl (writing to file)
# printf 'border=%s\nfocus=%s' "$LIGHTERBG" "$COL1" > "/tmp/dwl_colors"
printf 'focus=%s' "$COL1" > "/tmp/dwl_colors"
pkill -SIGUSR1 dwl

# Restart waybar
killall waybar
waybar --config "$HOME/.config/waybar/config_dwl.jsonc" &

# Change wallpaper
swaybg -i "$WALLPAPER" -m fill &

# Kill dunst
killall dunst
dunst &

# Select random dhikr for Firefox new tab page
dhikr=$(jq -r '.[]' "$FIREFOX_DIR/dhikr.json" | shuf -n 1)
sed -i "s/__DHIKR__/$dhikr/" "$FIREFOX_DIR/userContent.css"

