# Using ligatures fork `barsmonster/foot` (https://codeberg.org/dnkl/foot/pulls/2278)

[main]
font=JetBrainsMono NFM:style=Semibold:pixelsize=27
font-bold=JetBrainsMono NFM:style=Bold:pixelsize=27
font-italic=JetBrainsMono NFM:style=Semibold Italic:pixelsize=27
font-bold-italic=JetBrainsMono NFM:style=Bold Italic:pixelsize=27
# LEFTxTOPxRIGHTxBOTTOM
pad=20x20x20x10
line-height=35px

[tweak]
ligatures=yes

[cursor]
style=beam
blink=yes

[bell]
urgent=no
notify=no
command=no
command-focused=no

# Monokai Pro - Spectrum
[colors-dark]
alpha=0.90
background=222222
foreground=f7f1ff
selection-background=c1c0c0
selection-foreground=272822

# black
regular0=222222
bright0=69676c

# red
regular1=ff618d
bright1=ff618d

# green
regular2=7bd88f
bright2=7bd88f

# yellow
regular3=fce566
bright3=fce566

# blue
regular4=5ad4e6
bright4=5ad4e6

# magenta
regular5=948ae3
bright5=948ae3

# cyan
regular6=ae81ff
bright6=ae81ff

# white
regular7=c1c0c0
bright7=c1c0c0

